name: 💡 To suggest an idea
description: Suggest a new feature or improvement
labels: 💡 enhancement
body:
- type: textarea
  attributes:
    label: Description of the new feature / enhancement
    description: A clear and concise description of what the problem is that the new feature would solve. Describe why and how a user would use this new functionality (if applicable)
    value: |
        - 1
        - 2
        - 3
    
- type: textarea
  attributes:
    label: 📸 Screenshots
    description: Place any screenshots of the issue here if needed
  validations:
    required: false   

- type: textarea
  attributes:
    label: "⠀"
    description: "Form for user reactions, please do not change the text inside"
    placeholder: |
      ***
      If you like the idea, add a 👍 reaction to this post
    value: |
      ***
      If you like the idea, add a 👍 reaction to this post
