name: 🌐 Installer translation
description: Translate the installer into your language
labels: 🌐 New translation
body:
- type: input
  id: lang
  attributes:
    label: What language do you want to translate into?
    description: Also note the already added <a href="">languages</a>
    placeholder: e.g. English 
  validations:
    required: true
- type: input
  id: langpowershell
  attributes:
    label: Enter language name in PowerShell
    description: Enter the following command in the PowerShell terminal <kbd>$PSUICulture</kbd>, write the answer in the line below. For this to work, your Windows must be in this language.
    placeholder: e.g. en-US
  validations:
    required: true
- type: textarea
  attributes:
    label: 📝 Translation strings
    description: |
      Now you can start translating strings, a few notes before you start:
        - Translation strings start after an equals sign and are enclosed in quotation marks
        - There are variables before the equal sign, they do not need to be translated.
        - Also, if you come across characters <kbd>{0}</kbd>, <kbd>{1}</kbd>, <kbd>[Y/N]</kbd> or file names, then just skip them.
        
      Good luck to you. 
    value: |
      Welcome         = "
      ╔══════════════════════════════╗
      ║ Welcome to SpotX for Windows ║
      ╚══════════════════════════════╝"
      Incorrect       = "Oops, an incorrect value,"
      Incorrect2      = "enter again through "
      Download        = "Error downloading"
      Download2       = "Will re-request in 5 seconds..."
      Download3       = "Error again"
      Download4       = "Check your network settings and run the installation again"
      Download5       = "Downloading Spotify"
      Download6       = "Curl error"
      StopScrpit      = "Script is stopped"
      MsSpoti         = "The Microsoft Store version of Spotify has been detected which is not supported"
      MsSpoti2        = "Uninstall Spotify Windows Store edition [Y/N]"
      MsSpoti3        = "Automatically uninstalling Spotify MS..."
      MsSpoti4        = "Uninstalling Spotify MS..."
      Prem            = "Modification for premium account..."
      OldV            = "Found outdated version of Spotify"
      OldV2           = "Your Spotify {0} version is outdated, it is recommended to upgrade to {1}"
      OldV3           = "Want to update ? [Y/N]"
      AutoUpd         = "Automatic update to the recommended version"
      DelOrOver       = "Do you want to uninstall the current version of {0} or install over it? Y [Uninstall] / N [Install Over]"
      DelOld          = "Uninstalling old Spotify..."
      NewV            = "Unsupported version of Spotify found"
      NewV2           = "Your Spotify {0} version hasn't been tested yet, currently it's a stable {1} version"
      NewV3           = "Do you want to continue with {0} version (errors possible) ? [Y/N]"
      Recom           = "Do you want to install the recommended {0} version ? [Y/N]"
      DelNew          = "Uninstalling an untested Spotify..."
      DownSpoti       = "Downloading and installing Spotify"
      DownSpoti2      = "Please wait..."
      PodcatsOff      = "Off Podcasts"
      PodcastsOn      = "On Podcasts"
      PodcatsSelect   = "Do you want to disable podcasts, episodes and audiobooks from the main page? [Y/N]"
      DowngradeNote   = "It is recommended to block because Spotify was downgraded"
      UpdBlock        = "Spotify updates blocked"
      UpdUnblock      = "Spotify updates are not blocked"
      UpdSelect       = "Want to block Spotify updates? [Y/N]"
      CacheOn         = "Clear cache enabled ({0})"
      CacheOff        = "Clearing the cache is not enabled"
      CacheSelect     = "Want to set up automatic cache cleanup? [Y/N]"
      CacheDays       = "Cache older: XX days to be cleared "
      CacheDays2      = "Enter the number of days from 1 to 100"
      ModSpoti        = "Patching Spotify..."
      Error           = "Error"
      FileLocBroken   = "Location of Spotify files is broken, uninstall the client and run the script again"
      Spicetify       = "Spicetify detected"
      NoRestore       = "SpotX has already been installed, but files to recover xpui.js.bak and xpui.css.bak not found. `nPlease uninstall Spotify client and run Install.bat again"
      ExpSpotify      = "Experimental features operated by Spotify"
      ExpStandart     = "Experimental features of SpotX are not included"
      NoRestore2      = "SpotX has already been installed, xpui.bak not found. `nPlease uninstall Spotify client and run Install.bat again"
      UpdateBlocked   = "Spotify updates are already blocked"
      UpdateError     = "Failed to block updates"
      NoSpotifyExe    = "Could not find Spotify.exe"
      InstallComplete = "installation completed"
      HostInfo        = "Unwanted URLs found in hosts file"
      HostBak         = "Backing up hosts.bak..."
      HostDel         = "Trying to remove unwanted URLs from the original hosts file..."
      HostError       = "Something went wrong while editing the hosts file, edit it manually or run the script as administrator" 
    render: txt  
  validations:
    required: true        
